export const Research1 = "Investigating Structural Dynamics"
export const Research1Description = "Microscopy and diffraction techniques for identifying the presence of defects and inhomogeneities in both crystalline and amorphous materials."
export const Research2 = "Identifying Chemical Impurities"
export const Research2Description = "Spectroscopy and mass spectrometry techniques for identifying the presence of impurities at sensitivities approaching parts-per-billion levels."
export const Research3 = "Probing Emergent Phenomena"
export const Research3Description = "Advanced analytical techniques for observing exotic phenomena and states that can be harnessed for storing and manipulating information."