export const Research1 = "Research 1"
export const Research1Description = "Research1 Txt: This is a wider card with supporting text below as a natural lead-into additional content. This content is a little bit longer."
export const Research2 = "Research 2"
export const Research2Description = "Research2 Txt: This is a wider card with supporting text below as a natural lead-into additional content. This content is a little bit longer."
export const Research3 = "Research 3"
export const Research3Description = "Research3 Txt: This is a wider card with supporting text below as a natural lead-into additional content. This content is a little bit longer."