export const Research1 = "Understanding of Local Structure on Global Scale"
export const Research1Description = "Use of correlative microscopy and spectroscopy techniques to understand material structure from the atomic to the macro-scale."
export const Research2 = "Processing of Quantum Materials"
export const Research2Description = "Recreate fabrication steps required to construct quantum devices to obtain a mechanisting understanding of when impurities or disorder are introduced and how that impacts the lifetime of quantum states."
export const Research3 = "Probing Emergent Phenomena"
export const Research3Description = "Observe exotic phenomena and states that can be harnessed for storing and manipulating information."